config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin/rails', as: 'rails_admin'
  mount Blazer::Engine => '/admin/blazer', as: 'blazer'
  mount ActionCable.server => '/ws', as: 'websocket'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get 'signin', to: 'users/sessions#new', as: :signin
    post 'signin', to: 'users/sessions#create'
    delete 'signout', to: 'users/sessions#destroy', as: :signout
    get 'signup', to: 'users/registrations#new', as: :signup
  end

  root to: 'pages#root'

  namespace :admin do
    get '/', to: 'pages#root'

    get '/donation_id', to: 'pages#donation_id', as: :donation_id

    match '/jwt_token', to: 'pages#jwt_token', via: %i[get post], as: :jwt_token
    match '/websocket_server', to: 'pages#websocket_server', via: %i[get post], as: :websocket_server
    match '/donation_adder', to: 'pages#donation_adder', via: %i[get post], as: :donation_adder
    match '/command_executor', to: 'pages#command_executor', via: %i[get post], as: :command_executor
    match '/vk_cookies', to: 'pages#vk_cookies', via: %i[get post], as: :vk_cookies

    resources :audios, only: %i[index] do
      collection do
        get '/:manager/:id', to: 'audios#show', as: :audio
      end
    end
  end

  namespace :api do
    namespace :v2 do
      resources :discord_servers, only: %i[index show update]

      resources :audios, only: %i[index] do
        collection do
          get '/:manager/:id', to: 'audios#show', as: :audio
        end
      end

      resources :command_calls, only: %i[create]
    end
  end
end

app/views/admin/pages/audios.html.erb
<div class="row">
  <div class="col-3">
    <h4>Search parameters</h4>
    <%= form_with scope: 'audios', method: :get do |f| %>
      <div class="form-group">
        <%= f.label :manager, 'Audio manager:' %>
        <%= f.select :manager, options_from_collection_for_select(%w[vk], :to_s, :capitalize), {}, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :type, 'Request type:' %>
        <%= f.select :type, options_from_collection_for_select(%w[auto playlist audios post find wall artist], :to_s, :capitalize), {}, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :query, 'Query:' %>
        <%= f.text_field :query, class: 'form-control', placeholder: 'URL or search query', autocomplete: 'off' %>
      </div>
      <%= f.submit 'Load', class: 'btn btn-primary' %>
    <% end %>
  </div>
  <div class="col-6">
    <h4>Audios</h4>
    <% if @audios.present? %>
      <ul class="list-group list-group-flush">
        <% @audios.each do |el| %>
          <%= render_audio_item(el, class: 'list-group-item') %>
        <% end %>
      </ul>
    <% else %>
      <span>Nothing found</span>
    <% end %>
  </div>
  <div class="col-3">
    <h6>Audios download parameters</h6>
    <div class="form-group">
      <%= label_tag :format, 'Output format:' %>
      <%= select_tag :format, options_from_collection_for_select(FormatConverterService::FORMATS, :to_s, :to_s), class: 'form-control js-audio-download-format' %>
    </div>
  </div>
</div>

app/views/admin/pages/command_executor.html.erb
<h1><%= t('.admin_features') %></h1>
<h3><%= t('.command_executor') %></h1>

<%= form_with method: :post, local: true do |f| %>
  <div class="form-group">
    <%= f.label :shard, t('.shard_label') %>
    <%= f.select :shard, ActionCable.server.connections.map { |c| [c.current_shard.identifier] }, {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :payload, t('.payload_label') %>
    <%= f.text_area :payload, class: 'form-control', autocomplete: 'off' %>
  </div>
  <%= f.submit t('.execute_button'), class: 'btn btn-primary' %>
<% end %>

app/views/admin/pages/donation_adder.html.erb
<h1><%= t('.admin_features') %></h1>
<h3><%= t('.donation_adder') %></h1>

<%= form_with scope: 'donation', url: admin_donation_adder_path, local: true, method: :post do |f| %>
  <div class="form-group">
    <%= f.label :message, t('.message_label') %>
    <%= f.text_field :message, class: 'form-control', autocomplete: 'off' %>
  </div>
  <div class="form-group">
    <%= f.label :size, t('.size_label') %>
    <%= f.number_field :size, class: 'form-control', required: true, autocomplete: 'off', min: 0, value: 0 %>
  </div>
  <div class="form-group">
    <%= f.label :date, t('.date_label') %>
    <%= f.date_field :date, class: 'form-control', required: true, autocomplete: 'off', min: Date.current, value: Date.current %>
  </div>
  <%= f.submit t('.add_button'), class: 'btn btn-primary' %>
<% end %>

app/views/admin/pages/donation_id.html.erb
<h1><%= t('.admin_features') %></h1>
<h3><%= t('.donation_id') %></h1>

<%= form_with scope: 'donation', url: admin_donation_id_path, local: true, method: :get do |f| %>
  <div class="form-group">
    <%= f.label :id, t('.donation_id_label') %>
    <%= f.text_field :id, class: 'form-control', value: @id, autocomplete: 'off' %>
  </div>
  <div class="row">
    <div class="form-group col">
      <%= f.label :user_id, t('.user_id_label') %>
      <%= f.number_field :user_id, class: 'form-control', value: @user_id, autocomplete: 'off' %>
    </div>
    <div class="form-group col">
      <%= f.label :server_id, t('.server_id_label') %>
      <%= f.number_field :server_id, class: 'form-control', value: @server_id, autocomplete: 'off' %>
    </div>
  </div>
  <%= f.submit t('.convert_button'), method: :post, class: 'btn btn-primary' %>
<% end %>

app/views/admin/pages/jwt_token.html.erb
<h1><%= t('.admin_features') %></h1>
<h3><%= t('.jwt_token_generator') %></h1>

<%= form_with url: admin_jwt_token_path, local: true, method: :post do |f| %>
  <div class="form-group">
    <%= f.label :payload, t('.payload_label') %>
    <%= f.text_area :payload, class: 'form-control', value: @id, autocomplete: 'off' %>
  </div>
  <div class="form-group">
    <%= label_tag t('.token_label') %>
    <%= text_area_tag 'token', @token, class: 'form-control', autocomplete: 'off', disabled: 'true' %>
  </div>
  <%= f.submit t('.generate_button'), class: 'btn btn-primary' %>
<% end %>

app/views/admin/pages/root.html.erb
<h1><%= t('.admin_features') %></h1>

<ul>
  <li><%= link_to t('.donation_id'), admin_donation_id_path %></li>
  <li><%= link_to t('.jwt_token'), admin_jwt_token_path %></li>
  <li><%= link_to t('.audios'), admin_audios_path %></li>
  <li><%= link_to t('.websocket_server'), admin_websocket_server_path %></li>
  <li><%= link_to t('.donation_adder'), admin_donation_adder_path %></li>
  <li><%= link_to t('.command_executor'), admin_command_executor_path %></li>
  <li><%= link_to t('.vk_cookies'), admin_vk_cookies_path %></li>
</ul>

app/views/admin/pages/vk_cookies.html.erb
<h1><%= t('.admin_features') %></h1>
<h3><%= t('.vk_cookies') %></h1>

<%= form_with method: :post, local: true do |f| %>
  <div class="form-group">
    <%= f.label :cookies, t('.cookies_label') %>
    <%= f.text_area :cookies, class: 'form-control', autocomplete: 'off' %>
  </div>
  <%= f.submit t('.execute_button'), class: 'btn btn-primary', disabled: VK_AUDIO_MANAGER.client_initialized? %>
<% end %>

app/views/admin/pages/websocket_server.html.erb
<h1><%= t('.admin_features') %></h1>
<h3><%= t('.websocket_server') %></h1>

<%= form_with method: :post, local: true do |f| %>
  <div class="row mt-5">
    <div class="col-12 col-sm-4 col-md-3">
      <div class="btn-group-vertical w-100 mb-4">
        <%= f.button name: 'websocket_server[action]', value: 'reload', class: 'btn btn-primary', data: {} do %>
          <span><%= t('.reload_button') %></span>
          <span class="float-right ml-3"><%= fa_icon 'sync' %></span>
        <% end %>
        <%= f.button name: 'websocket_server[action]', value: 'update_data', class: 'btn btn-default', data: {} do %>
          <span><%= t('.update_button') %></span>
          <span class="float-right ml-3"><%= fa_icon 'retweet' %></span>
        <% end %>
        <%= f.button name: 'websocket_server[action]', value: 'disconnect', class: 'btn btn-danger', data: { confirm: 'Are you sure?' } do %>
          <span><%= t('.disconnect_button') %></span>
          <span class="float-right ml-3"><%= fa_icon 'sign-out-alt' %></span>
        <% end %>
        <%= f.button name: 'websocket_server[action]', value: 'restart', class: 'btn btn-danger', data: { confirm: 'Are you sure?' } do %>
          <span><%= t('.restart_button') %></span>
          <span class="float-right ml-3"><%= fa_icon 'sign-out-alt' %></span>
        <% end %>
        <%= f.button name: 'websocket_server[action]', value: 'stop', class: 'btn btn-danger', data: { confirm: 'Are you sure?' } do %>
          <span><%= t('.stop_button') %></span>
          <span class="float-right ml-3"><%= fa_icon 'sign-out-alt' %></span>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-sm-8 offset-md-1">
      <div class="card">
        <div class="card-header">
          <p>
            <%= t('.amount_of_shards') %>
            <b><%= ActionCable.server.connections.size %></b>
          </p>
          <p>
            <%= t('.amount_of_servers') %>
            <b><%= ActionCable.server.connections.sum { |c| c.current_shard.servers_count.to_i } %></b>
          </p>
          <p>
            <%= t('.amount_of_cached_servers') %>
            <b><%= ActionCable.server.connections.sum { |c| c.current_shard.cached_servers_count.to_i } %></b>
          </p>
          <p>
            <%= t('.amount_of_active_servers') %>
            <b><%= ActionCable.server.connections.sum { |c| c.current_shard.active_servers_count.to_i } %></b>
          </p>
        </div>
        <div class="overflow-auto">
          <table class="card-body table table-striped table-bordered mb-0 js-table-sorter-binder">
            <thead class="text-center">
              <tr>
                <td rowspan=2 class="align-middle"><%= t('.shards') %></td>
                <td colspan=3><%= t('.server_counts') %></td>
              </tr>
              <tr>
                <td><%= t('.total') %></td>
                <td><%= t('.cached') %></td>
                <td><%= t('.active') %></td>
              </tr>
            </thead>
            <tbody>
              <% ActionCable.server.connections.each do |c| %>
                <tr>
                  <td>
                    <div class="custom-control custom-checkbox">
                      <%= f.check_box 'websocket_server[clients]', { multiple: true, checked: true, class: 'custom-control-input' }, c.current_shard.identifier, nil %>
                      <label class="custom-control-label" for="websocket_server[clients]_<%= c.current_shard.identifier %>"><%= c.current_shard.identifier %></label>
                    </div>
                  </td>
                  <td><%= c.current_shard.servers_count %></td>
                  <td><%= c.current_shard.cached_servers_count %></td>
                  <td><%= c.current_shard.active_servers_count %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= javascript_pack_tag 'admin/websocket_server', 'data-turbolinks-track': 'reload' %>