config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin/rails', as: 'rails_admin'
  mount Blazer::Engine => '/admin/blazer', as: 'blazer'
  mount ActionCable.server => '/ws', as: 'websocket'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get 'signin', to: 'users/sessions#new', as: :signin
    post 'signin', to: 'users/sessions#create'
    delete 'signout', to: 'users/sessions#destroy', as: :signout
    get 'signup', to: 'users/registrations#new', as: :signup
  end

  root to: 'pages#root'

  namespace :admin do
    get '/', to: 'pages#root'

    get '/donation_id', to: 'pages#donation_id', as: :donation_id

    match '/jwt_token', to: 'pages#jwt_token', via: %i[get post], as: :jwt_token
    match '/websocket_server', to: 'pages#websocket_server', via: %i[get post], as: :websocket_server
    match '/donation_adder', to: 'pages#donation_adder', via: %i[get post], as: :donation_adder
    match '/command_executor', to: 'pages#command_executor', via: %i[get post], as: :command_executor
    match '/vk_cookies', to: 'pages#vk_cookies', via: %i[get post], as: :vk_cookies

    resources :audios, only: %i[index] do
      collection do
        get '/:manager/:id', to: 'audios#show', as: :audio
      end
    end
  end

  namespace :api do
    namespace :v2 do
      resources :discord_servers, only: %i[index show update]

      resources :audios, only: %i[index] do
        collection do
          get '/:manager/:id', to: 'audios#show', as: :audio
        end
      end

      resources :command_calls, only: %i[create]
    end
  end
end

app/views/layouts/admin_application/_topbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <%= link_to t('.dusic'), root_path, class: 'navbar-brand' %>
  <ul class="navbar-nav collapse navbar-collapse">
    <li class="nav-item">
      <%= link_to t('.home'), root_path, class: 'nav-link' %>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    <% if current_user %>
      <li class="nav-item dropdown">
        <span class="nav-link dropdown-toggle" id="profileDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= t('.profile') %>
        </span>
        <div class="dropdown-menu dropdown-menu-right position-absolute" aria-labelledby="profileDropdown">
          <span class="dropdown-item-text text-nowrap">
            <%= t('.logged_in_as_html', email: current_user.email) %>
          </span>
          <div class="dropdown-divider"></div>
          <% if current_user.admin %>
            <%= link_to t('.rails_admin'), rails_admin_path, class: 'dropdown-item', 'data-turbolinks': 'false' %>
            <%= link_to t('.blazer'), blazer_path, class: 'dropdown-item', 'data-turbolinks': 'false' %>
            <%= link_to t('.admin_features'), admin_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
          <% end %>
          <%= button_to t('.signout'), signout_path, method: :delete, class: 'dropdown-item' %>
        </div>
      </li>
    <% end %>
  </ul>
</nav>